import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  async redirects() {
    return [
      // ── URL restructure 2026-03-08 ──
      { source: "/industries", destination: "/industries-we-offer-marketing-services-for", permanent: true },
      { source: "/areas", destination: "/services-areas-we-offer-marketing-services-in", permanent: true },
      { source: "/free-seo-audit", destination: "/the-free-human%2Bai-seo-marketing-review", permanent: true },
      { source: "/marketing-checklist-2026", destination: "/master-marketing-checklist-last-updated-2026", permanent: true },
      { source: "/roi-calculator", destination: "/annual-marketing-spend-roi-calculator", permanent: true },
      { source: "/blog", destination: "/the-marketing-blog", permanent: true },
      { source: "/ai", destination: "/artificial-intelligence-marketing-services-offered", permanent: true },
      { source: "/blog/:path*", destination: "/the-marketing-blog/:path*", permanent: true },
      { source: "/industries/:path*", destination: "/industries-we-offer-marketing-services-for/:path*", permanent: true },

      // ── Old category/breadcrumb routes ──
      { source: "/Web Design", destination: "/services/web-design-nyc", permanent: true },
      { source: "/Web%20Design", destination: "/services/web-design-nyc", permanent: true },
      { source: "/Branding", destination: "/services/brand-strategy-identity-in-nyc", permanent: true },
      { source: "/Strategy", destination: "/services/business-strategy-consulting-in-nyc", permanent: true },
      { source: "/Services", destination: "/services", permanent: true },
      { source: "/Services/SEO", destination: "/services/search-engine-optimization-seo-nyc", permanent: true },
      { source: "/Services/SEO/:path*", destination: "/services/search-engine-optimization-seo-nyc", permanent: true },
      { source: "/Content%20Marketing", destination: "/services/content-marketing-in-nyc", permanent: true },
      { source: "/Content Marketing", destination: "/services/content-marketing-in-nyc", permanent: true },
      { source: "/More", destination: "/", permanent: true },
      { source: "/More/Service%20Areas", destination: "/services-areas-we-offer-marketing-services-in", permanent: true },
      { source: "/More/Service Areas", destination: "/services-areas-we-offer-marketing-services-in", permanent: true },

      // ── Old service sub-pages → new service slugs ──
      { source: "/services/web-design", destination: "/services/web-design-nyc", permanent: true },
      { source: "/services/website-design", destination: "/services/website-design-in-nyc", permanent: true },
      { source: "/services/mobile-responsive-web-design", destination: "/services/mobile-responsive-web-design-in-nyc", permanent: true },
      { source: "/services/website-optimization", destination: "/services/website-optimization-in-nyc", permanent: true },
      { source: "/services/landing-page-design", destination: "/services/landing-page-design-in-nyc", permanent: true },
      { source: "/services/micro-site-website-design", destination: "/services/micro-site-website-design-in-nyc", permanent: true },
      { source: "/services/seo", destination: "/services/search-engine-optimization-seo-nyc", permanent: true },
      { source: "/services/seo-services", destination: "/services/seo-services-in-nyc", permanent: true },
      { source: "/services/local-seo", destination: "/services/local-seo-in-nyc", permanent: true },
      { source: "/services/technical-seo", destination: "/services/technical-seo-in-nyc", permanent: true },
      { source: "/services/on-page-seo", destination: "/services/on-page-seo-optimization-in-nyc", permanent: true },
      { source: "/services/on-page-seo-optimization", destination: "/services/on-page-seo-optimization-in-nyc", permanent: true },
      { source: "/services/off-page-seo", destination: "/services/off-page-seo-and-link-building-in-nyc", permanent: true },
      { source: "/services/keyword-research", destination: "/services/keyword-research-and-strategy-in-nyc", permanent: true },
      { source: "/services/keyword-research-and-strategy", destination: "/services/keyword-research-and-strategy-in-nyc", permanent: true },
      { source: "/services/seo-audit", destination: "/services/seo-audit-and-analysis-in-nyc", permanent: true },
      { source: "/services/seo-audit-and-analysis", destination: "/services/seo-audit-and-analysis-in-nyc", permanent: true },
      { source: "/services/logo-design", destination: "/services/logo-design-in-nyc", permanent: true },
      { source: "/services/brand-naming", destination: "/services/brand-naming-and-rebranding-in-nyc", permanent: true },
      { source: "/services/brand-naming-and-rebranding", destination: "/services/brand-naming-and-rebranding-in-nyc", permanent: true },
      { source: "/services/branding", destination: "/services/brand-strategy-identity-in-nyc", permanent: true },
      { source: "/services/content-marketing", destination: "/services/content-marketing-in-nyc", permanent: true },
      { source: "/services/video-content-production", destination: "/services/video-content-production-in-nyc", permanent: true },
      { source: "/services/content-strategy", destination: "/services/content-strategy-and-planning-in-nyc", permanent: true },
      { source: "/services/content-strategy-and-planning", destination: "/services/content-strategy-and-planning-in-nyc", permanent: true },
      { source: "/services/social-media", destination: "/services/social-media-marketing-in-nyc", permanent: true },
      { source: "/services/social-media-management", destination: "/services/social-media-management-in-nyc", permanent: true },
      { source: "/services/social-media-marketing", destination: "/services/social-media-marketing-in-nyc", permanent: true },
      { source: "/services/social-media-marketing-strategy", destination: "/services/social-media-marketing-strategy-in-nyc", permanent: true },
      { source: "/services/social-media-advertising", destination: "/services/social-media-advertising-in-nyc", permanent: true },
      { source: "/services/social-media-content-creation", destination: "/services/social-media-content-creation-in-nyc", permanent: true },
      { source: "/services/ppc-advertising", destination: "/services/ppc-advertising-in-nyc", permanent: true },
      { source: "/services/ppc", destination: "/services/digital-advertising-ppc-in-nyc", permanent: true },
      { source: "/services/paid-search-campaigns", destination: "/services/paid-search-campaigns-in-nyc", permanent: true },
      { source: "/services/google-ads", destination: "/services/google-ads-management-in-nyc", permanent: true },
      { source: "/services/email-marketing", destination: "/services/email-marketing-automation-in-nyc", permanent: true },
      { source: "/services/email-marketing-campaigns", destination: "/services/email-marketing-campaigns-in-nyc", permanent: true },
      { source: "/services/email-campaign-management", destination: "/services/email-campaign-management-in-nyc", permanent: true },
      { source: "/services/marketing-automation", destination: "/services/marketing-automation-in-nyc", permanent: true },
      { source: "/services/drip-campaigns", destination: "/services/drip-campaigns-and-nurture-sequences-in-nyc", permanent: true },
      { source: "/services/drip-campaigns-and-nurture-sequences", destination: "/services/drip-campaigns-and-nurture-sequences-in-nyc", permanent: true },
      { source: "/services/online-reputation-management", destination: "/services/online-reputation-management-in-nyc", permanent: true },
      { source: "/services/online-reputation", destination: "/services/online-reputation-management-in-nyc", permanent: true },
      { source: "/services/press-release", destination: "/services/press-release-writing-and-distribution-in-nyc", permanent: true },
      { source: "/services/press-release-writing-and-distribution", destination: "/services/press-release-writing-and-distribution-in-nyc", permanent: true },
      { source: "/services/media-outreach", destination: "/services/media-outreach-in-nyc", permanent: true },
      { source: "/services/digital-pr-campaigns", destination: "/services/digital-pr-campaigns-in-nyc", permanent: true },
      { source: "/services/digital-pr", destination: "/services/digital-pr-campaigns-in-nyc", permanent: true },
      { source: "/services/public-relations", destination: "/services/public-relations-reputation-in-nyc", permanent: true },
      { source: "/services/google-analytics", destination: "/services/google-analytics-setup-and-management-in-nyc", permanent: true },
      { source: "/services/google-analytics-setup-and-management", destination: "/services/google-analytics-setup-and-management-in-nyc", permanent: true },
      { source: "/services/marketing-technology-consulting", destination: "/services/marketing-technology-consulting-in-nyc", permanent: true },
      { source: "/services/performance-tracking", destination: "/services/performance-tracking-and-kpis-in-nyc", permanent: true },
      { source: "/services/performance-tracking-and-kpis", destination: "/services/performance-tracking-and-kpis-in-nyc", permanent: true },
      { source: "/services/analytics", destination: "/services/analytics-technology-in-nyc", permanent: true },
      { source: "/services/business-growth-consulting", destination: "/services/business-growth-consulting-in-nyc", permanent: true },
      { source: "/services/swot-analysis", destination: "/services/swot-analysis-in-nyc", permanent: true },
      { source: "/services/strategic-business-planning", destination: "/services/strategic-business-planning-in-nyc", permanent: true },
      { source: "/services/scaling-and-expansion-strategy", destination: "/services/scaling-and-expansion-strategy-in-nyc", permanent: true },
      { source: "/services/influencer-marketing", destination: "/services/influencer-marketing-in-nyc", permanent: true },

      // ── Old area routes ──
      { source: "/nyc-marketing-company-service-areas", destination: "/services-areas-we-offer-marketing-services-in", permanent: true },
      { source: "/areas/bronx", destination: "/services-areas-we-offer-marketing-services-in/bronx-marketing-company", permanent: true },
      { source: "/areas/brooklyn", destination: "/services-areas-we-offer-marketing-services-in/brooklyn-marketing-company", permanent: true },
      { source: "/areas/queens", destination: "/services-areas-we-offer-marketing-services-in/queens-marketing-company", permanent: true },
      { source: "/areas/manhattan", destination: "/services-areas-we-offer-marketing-services-in/manhattan-marketing-company", permanent: true },
      { source: "/areas/staten-island", destination: "/services-areas-we-offer-marketing-services-in/staten-island-marketing-company", permanent: true },
      { source: "/areas/long-island", destination: "/services-areas-we-offer-marketing-services-in/long-island-marketing-company", permanent: true },
      { source: "/areas/westchester", destination: "/services-areas-we-offer-marketing-services-in/westchester-marketing-company", permanent: true },
      { source: "/areas/:path*", destination: "/services-areas-we-offer-marketing-services-in/:path*", permanent: true },

      // ── Old /service-areas/ links (pre-rebrand) ──
      { source: "/service-areas/nyc-digital-marketing-agency", destination: "/services-areas-we-offer-marketing-services-in/manhattan-marketing-company", permanent: true },
      { source: "/service-areas/queens-digital-marketing-agency", destination: "/services-areas-we-offer-marketing-services-in/queens-marketing-company", permanent: true },
      { source: "/service-areas/brooklyn-digital-marketing-agency", destination: "/services-areas-we-offer-marketing-services-in/brooklyn-marketing-company", permanent: true },
      { source: "/service-areas/long-island-digital-marketing-agency", destination: "/services-areas-we-offer-marketing-services-in/long-island-marketing-company", permanent: true },
      { source: "/service-areas/hoboken-digital-marketing-agency", destination: "/services-areas-we-offer-marketing-services-in/hoboken-marketing-company", permanent: true },
      { source: "/service-areas/:path*", destination: "/services-areas-we-offer-marketing-services-in", permanent: true },

      // ── Missing redirects ──
      { source: "/services", destination: "/nyc-marketing-company-services-list", permanent: true },
      { source: "/marketing-101", destination: "/nyc-marketing-101-guide", permanent: true },
      { source: "/nyc-digital-marketing-agency-services-offered-by-consortium-nyc", destination: "/nyc-marketing-company-services-list", permanent: true },

      // ── Old misc pages ──
      { source: "/nyc-digital-marketing-agency", destination: "/", permanent: true },
      { source: "/nyc-digital-marketing-agency/:path*", destination: "/", permanent: true },
      { source: "/nyc-digital-marketing-agency-faqs", destination: "/nyc-marketing-company-faqs", permanent: true },
      { source: "/about-digital-marketing-agency", destination: "/about", permanent: true },
      { source: "/about-marketing-company-consortium-nyc", destination: "/about", permanent: true },
      { source: "/about-digital-marketing-agency-consortium-nyc", destination: "/about", permanent: true },
      { source: "/contact-nyc-marketing-company-consortium-nyc", destination: "/contact", permanent: true },
      { source: "/contact-nyc-digital-marketing-agency-consortium-nyc", destination: "/contact", permanent: true },
      { source: "/contact-nyc-marketing-company", destination: "/contact", permanent: true },
      { source: "/pricing", destination: "/nyc-marketing-pricing-guide", permanent: true },
      { source: "/faq", destination: "/nyc-marketing-company-faqs", permanent: true },
      { source: "/faqs", destination: "/nyc-marketing-company-faqs", permanent: true },
      { source: "/portfolio", destination: "/nyc-marketing-company-portfolio", permanent: true },
    ];
  },
};

export default nextConfig;
